services:
  - type: web
    name: college-event-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - path: "/*"
        destination: /index.html
        type: rewrite
