services:
  - type: web
    name: college-event-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://campus-event-tracker-backend.onrender.com
      - key: VITE_APP_NAME
        value: Campus Event Tracker
    redirects:
      - source: "/*"
        destination: "/index.html"
        type: "rewrite"
